
apiVersion: v2
name: monitoring-stack
version: 1.0.0
dependencies:
  - name: kube-prometheus-stack
    version: "55.5.0"  # Current stable
    repository: "https://prometheus-community.github.io/helm-charts"